# Generated by Django 5.2.9 on 2026-01-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='inst_image',
            field=models.ImageField(default='default.jpg', upload_to='instructor/'),
            preserve_default=False,
        ),
    ]
